### ISSUE TITLE
Specified semester not respected?

### ISSUE THREAD

**Issue by EnhancedJax** [borisonwong/hkutimetable2023#1]
![Screenshot 2024-07-30 at 12 37 27 PM](https://github.com/user-attachments/assets/86fb2c0d-323b-4a0c-950c-9ccda5620a82)

Chose course semester to be 2, result semester includes subclasses from semester 1. Is this a bug?

**Comment by borisonwong** [comment]
Thanks for letting me know this issue, yes this is a bug and now it is fixed :)
